<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>@yield('title')</title>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 12px; color: #333; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #22C55E; padding-bottom: 10px; }
        .logo { font-size: 24px; font-weight: bold; color: #111827; }
        .logo span { color: #22C55E; }
        .title { font-size: 18px; font-weight: bold; margin-top: 10px; }
        .meta { margin-bottom: 20px; font-size: 11px; color: #666; }
        .summary { margin-bottom: 20px; padding: 10px; background-color: #f9f9f9; border: 1px solid #ddd; }
        table { w-full: 100%; width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; font-weight: bold; }
        .footer { text-align: center; margin-top: 30px; font-size: 10px; color: #999; border-top: 1px solid #ddd; padding-top: 10px; }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .font-bold { font-weight: bold; }
    </style>
</head>
<body>
    <div class="header">
        <div class="logo">Warm<span>Up</span></div>
        <div class="title">@yield('title')</div>
    </div>

    <div class="meta">
        <strong>Generated on:</strong> {{ \Carbon\Carbon::now('Asia/Karachi')->gymDateTimeFormat() }}<br>
        @yield('filters')
    </div>

    @yield('summary')

    @yield('content')

    <div class="footer">
        Generated by WarmUp Gym Management System
    </div>
</body>
</html>
